name: Build and Test with AIE tools on Ryzen AI

on:
  push:
    branches:
      - main
      - test-ryzen-ai
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit).
  group: ci-build-test-ryzenai-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  DEBIAN_FRONTEND: noninteractive
  XILINXD_LICENSE_FILE: /opt/xilinx/Xilinx.lic

jobs:
  build-repo:
    name: Build and Test with AIE tools on Ryzen AI

    runs-on: amd7940hs

    steps:

      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Setup environment
        run: |
          python3.10 -m venv air-venv
          source air-venv/bin/activate
          pip cache purge
          pip install --upgrade pip
          pip install lit cmake joblib bfloat16

      - name: Get mlir-aie
        id: clone-mlir-aie
        run: |
          utils/clone-mlir-aie.sh
          source air-venv/bin/activate
          pushd mlir-aie
          pip install -r python/requirements.txt
          popd

      - name: Get LLVM
        id: clone-llvm
        run: utils/clone-llvm.sh
        shell: bash
        
      - name: Build and Install LLVM
        run: utils/github-build-llvm.sh

      - name: Build and Install mlir-aie
        run: |
          source air-venv/bin/activate
          pushd mlir-aie

          mkdir build
          pushd build

          export PATH=$PATH:/opt/Xilinx/Vitis/2023.2/bin:/opt/Xilinx/Vitis/2023.2/aietools/bin
          cmake .. \
            -GNinja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DPython3_EXECUTABLE=$(which python) \
            -DCMAKE_INSTALL_PREFIX=$PWD/../install \
            -DCMAKE_C_COMPILER=clang-15 \
            -DCMAKE_CXX_COMPILER=clang++-15 \
            -DCMAKE_ASM_COMPILER=clang-15 \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_EXE_LINKER_FLAGS_INIT="-fuse-ld=lld" \
            -DCMAKE_MODULE_LINKER_FLAGS_INIT="-fuse-ld=lld" \
            -DCMAKE_SHARED_LINKER_FLAGS_INIT="-fuse-ld=lld" \
            -DCMAKE_MODULE_PATH=$PWD/../cmake/modulesXilinx \
            -DLLVM_EXTERNAL_LIT=$(which lit) \
            -DMLIR_DIR=$PWD/../../llvm/install/lib/cmake/mlir/ \
            -DXRT_ROOT=/opt/xilinx/xrt \
            -DAIE_ENABLE_PYTHON_PASSES=OFF \
            -DAIE_ENABLE_XRT_PYTHON_BINDINGS=ON \
            -DAIE_INCLUDE_INTEGRATION_TESTS=OFF

          ninja install
          ninja check-aie
          popd

          # rm -rf build
          popd

      # Build the repo test target in debug mode to build and test.
      - name: Build and test (Assert)
        run: |
          source air-venv/bin/activate
          mkdir build_assert
          pushd build_assert

          export PATH=$PATH:/opt/Xilinx/Vitis/2023.2/bin:/opt/Xilinx/Vitis/2023.2/aietools/bin
          cmake .. \
            -GNinja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DPython3_EXECUTABLE=$(which python) \
            -DCMAKE_INSTALL_PREFIX=$PWD/../install \
            -DCMAKE_C_COMPILER=clang-15 \
            -DCMAKE_CXX_COMPILER=clang++-15 \
            -DCMAKE_ASM_COMPILER=clang-15 \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_EXE_LINKER_FLAGS_INIT="-fuse-ld=lld" \
            -DCMAKE_MODULE_LINKER_FLAGS_INIT="-fuse-ld=lld" \
            -DCMAKE_SHARED_LINKER_FLAGS_INIT="-fuse-ld=lld" \
            -DCMAKE_MODULE_PATH=$PWD/../mlir-aie/cmake/modulesXilinx \
            -DLLVM_EXTERNAL_LIT=$(which lit) \
            -DMLIR_DIR=$PWD/../llvm/install/lib/cmake/mlir/ \
            -DAIE_DIR=$PWD/../mlir-aie/install/lib/cmake/aie/ \
            -Dx86_64_TOOLCHAIN_FILE=$PWD/../cmake/modules/toolchain_x86_64.cmake \
            -DLibXAIE_ROOT=$PWD/../mlir-aie/install/runtime_lib/x86_64/xaiengine \
            -DAIR_RUNTIME_TARGETS:STRING="x86_64" \
            -DXRT_ROOT=/opt/xilinx/xrt \
            -DENABLE_RUN_XRT_TESTS=ON
          ninja install
          ninja check-air-cpp
          ninja check-air-mlir
          ninja check-air-python
          env
          ninja check-air-e2e
          popd
          rm -rf build_assert
